---
# Activate or deactivate OnlyProxyJoin.
use-onlyproxyjoin: true

# Proxy address
proxy-address: "127.0.0.1"

# Kick message when player is not connected to the proxy
kick-message: "Please join over the proxy."
...